# Generated by Django 5.0 on 2023-12-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='giamhieu',
            fields=[
                ('giamhieu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('chuc_vu', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('nhiem_vu', models.CharField(max_length=100)),
            ],
        ),
    ]
